/**
 * Generated by @openapi-codegen
 *
 * @version v1
 */
export type AuthDto = {
  login?: string | null;
  password?: string | null;
};

/**
 * @format int32
 */
export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type GetShiftDto = {
  dayOfWeek?: DayOfWeek;
  /**
   * @format int32
   */
  hours?: number;
  free?: boolean;
};

export type Payment = {
  id?: string | null;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  status?: PaymentStatus;
  type?: PaymentType;
  /**
   * @format int32
   */
  numericId?: number;
  /**
   * @format int32
   */
  price?: number;
  userId?: string | null;
  user?: User;
};

export type PaymentDto = {
  status?: PaymentStatus;
  type?: PaymentType;
  /**
   * @format int32
   */
  price?: number;
  userId?: string | null;
};

/**
 * @format int32
 */
export type PaymentStatus = 0 | 1 | 2;

/**
 * @format int32
 */
export type PaymentType = 0 | 1;

export type Shift = {
  id?: string | null;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  userId?: string | null;
  targetWeekId?: string | null;
  targetWeek?: Week;
  weeks?: string[] | null;
  weeksList?: Week[] | null;
};

export type User = {
  id?: string | null;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  fullName?: string | null;
  login?: string | null;
  role?: UserRole;
  status?: UserStatus;
  shiftId?: string | null;
};

export type UserDto = {
  fullName?: string | null;
  login?: string | null;
  password?: string | null;
  role?: UserRole;
};

/**
 * @format int32
 */
export type UserRole = 0 | 1 | 2 | 3 | 4;

/**
 * @format int32
 */
export type UserStatus = 0 | 1 | 2 | 3;

export type Week = {
  id?: string | null;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  /**
   * @format int32
   */
  monday?: number;
  /**
   * @format int32
   */
  tuesday?: number;
  /**
   * @format int32
   */
  wednesday?: number;
  /**
   * @format int32
   */
  thursday?: number;
  /**
   * @format int32
   */
  friday?: number;
  /**
   * @format int32
   */
  saturday?: number;
  /**
   * @format int32
   */
  sunday?: number;
  shiftId?: string | null;
  shift?: Shift;
};
